server:
  port: 8080

spring:

  application:
    name: Test_Bank_REST

  datasource:
    url: jdbc:postgresql://localhost:5432/TestBank
    username: tatar
    password: nfnfh15277
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    show-sql: false
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default-schema: dev
        format-sql: true