openapi: 3.0.0
info:
  title: Bank Cards Management API
  description: API для управления банковскими картами
  version: 1.0.0

servers:
  - url: http://localhost:8080/api
    description: Development server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT